import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import { gordita, bodoni } from "@/assets/fonts";
import { Header } from "@/common/components/skeleton/header";
import { Footer } from "@/common/components/skeleton/footer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
    title: "Omoyeni Website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${gordita.variable} ${bodoni.variable} font-gordita`}>
                <Toaster position='top-right' />
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
