import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import { gorditaRegular } from "../assets/fonts";
import { Header } from "@/common/components/skeleton/header";
import { Footer } from "@/common/components/skeleton/footer";

export const metadata: Metadata = {
    title: "Omoyeni Website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={gorditaRegular.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
